POST http://localhost:8088/mobe/authent/user
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"login":"py", "mdp":"py"}

### récuperer le token dans les response headers et le coller pour la requete checktoken

