server: 
  port: 8080

spring:
  jpa:
    database-platform: fr.miage.orleans.isi.projet.authentificationws.config.SQLiteDialect
    hibernate:
      ddl-auto: update #create-drop
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
      connection: 
        autocommit: true
    show-sql: true
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:../data/db_musee.db

eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka #localhost
      defaultZone: http://eureka-discovery:8761/eureka #docker
